### PR TITLE
Update to StrideArraysCore.jl v0.5.0 (no more silent `@inbouds`)

### PR DESCRIPTION
**Pull request by MasonProtter**
xref https://github.com/JuliaSIMD/StrideArraysCore.jl/pull/43

### CODE REVIEW

**Comment by chriselrod** [comment]
Is there a compelling reason to drop 0.4 support?

**Comment by MasonProtter** [comment]
> Is there a compelling reason to drop 0.4 support?

Not really, no.

**Comment by MasonProtter** [comment]
The reason I dropped `0.4` was that I didn't want the package resolver to be the one choosing whether or not people end up with boundschecking or not, but if you prefer broad compat bounds that's fine. 

It looks like the method for `exp` defined here: https://github.com/JuliaSIMD/StrideArrays.jl/blob/0d04ac3a0a97e26b00931ae75818643d64299340/src/miscellaneous.jl#L234 doesn't work because `exp!` is limited to just `StridedArray` which is a hardcoded union. 

Did that test ever work? We'll either need our own version of `exp!` or to remove that method.

**Comment by chriselrod** [comment]
> The reason I dropped `0.4` was that I didn't want the package resolver to be the one choosing whether or not people end up with boundschecking or not, but if you prefer broad compat bounds that's fine.
> 
> It looks like the method for `exp` defined here:
> 
> https://github.com/JuliaSIMD/StrideArrays.jl/blob/0d04ac3a0a97e26b00931ae75818643d64299340/src/miscellaneous.jl#L234
> doesn't work because `exp!` is limited to just `StridedArray` which is a hardcoded union.
> 
> Did that test ever work? We'll either need our own version of `exp!` or to remove that method I think.

I'm guessing it did when I added it, but feel free to remove it.

**Pull request merged**
